/* eslint-disable @typescript-eslint/ban-ts-comment */
import type { Metadata } from 'next'
import { Antonio } from 'next/font/google'
// @ts-ignore
import './globals.css'

import { ThemeProvider } from '~/providers/ThemeProvider'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import ProviderReactQuery from '~/providers/ProviderReactQuery'
import ToasterCustom from '~/components/shared/ToasterCustom'
import GlobalLoadingOverlay from '~/components/shared/GlobalLoadingOverlay'

const font = Antonio({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-heading3',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${font.variable} ${font.variable} antialiased overflow-x-hidden`}
        suppressHydrationWarning
      >
        <ToasterCustom />
        <GlobalLoadingOverlay />
        <ProviderReactQuery>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <NuqsAdapter> {children}</NuqsAdapter>
          </ThemeProvider>
        </ProviderReactQuery>
      </body>
    </html>
  )
}
